name: tool-rental-pos-system
services:
  frontend:
    build: ./pos
    ports:
      - "8081:8080"

  api:
    build: ./api
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8082:8080"

  database:
    build: ./database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: toolrentalpass
      POSTGRES_USER: toolrentaluser
      POSTGRES_DB: toolrentaldb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toolrentaluser -d toolrentaldb"]
      interval    : 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
