name: teamviewer-remote-desktop-shop
services:
  frontend:
    build: ./store
    ports:
      - "8081:8080"

  api:
    build: ./api
    ports:
      - "8082:8080"

  database:
    build: ./database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: team
      POSTGRES_USER: team
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U team"]
      interval    : 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
